---
- name: Install MongoDB on Amazon Linux 2023 via SSM
  hosts: all
  become: yes

  tasks:
    - name: Add MongoDB 6.0 repo (EL9)
      yum_repository:
        name: mongodb-org-6.0
        description: MongoDB Repository
        baseurl: https://repo.mongodb.org/yum/redhat/9/mongodb-org/6.0/x86_64/
        gpgcheck: yes
        enabled: yes
        gpgkey: https://pgp.mongodb.com/server-6.0.asc

    - name: Refresh dnf cache
      dnf:
        update_cache: yes

    - name: Install MongoDB
      dnf:
        name: mongodb-org
        state: present

    - name: Enable and start MongoDB
      service:
        name: mongod
        state: started
        enabled: yes
